pull_request_rules:
  - name: automatic merge on CI success and review
    conditions:
      - status-success~=Travis
      - title~=drupal/core
      - title~=SECURITY
      - author=violinist-bot
    actions:
      merge:
        method: merge
